ignore:
  - "**/swingGUI.scala"
  - "**/fxGUI.scala"
  - "**/TileLabel.scala"
  - "**/fenDemo.worksheet.sc"
  - "**/model.worksheet.sc"
  - "**/TileLabel.scala"
  - "**/Chess.scala"
  - "**/resources/"
  - "**/ChessModule.scala"
  - "**/BaseControllerModule.scala"
  - "**/ControllerModule.scala"
  - "**/LegalityModule.scala"
  - "**/PersistenceModule.scala"
  - "**/*Communicating*/"
  - "**/**Service.scala"
  - "**/**Routes.scala"
  - "**/messages/**"
  - "**/**Interface.scala"
  - "**/GameData.scala"
  - "**/UserDao.scala"
  - "**/SessionDao.scala"

coverage:
  status:
    patch:
      default:
        target: 75%