services:

  mongodb:  
    image: mongo:6.0.5
    restart: always
    container_name: mongodb
    ports:
      - "27017:27017"  
    networks:
      - chess-network
    volumes:
      - mongodb-data:/data/db
    env_file:
      - ./docker/secrets/mongo.env
    healthcheck:
      test: ["CMD-SHELL", "echo 'here'"]
      interval: 5s
      timeout: 30s
      retries: 10
      start_period: 30s

  persistence:
    image: chess-persistence:mongodb
    build:
      context: .
      dockerfile: docker/service.Dockerfile
      args:
        - SERVICE=persistence
        - SERVICE_API_PORT=8083
      cache_from:
        - chess-persistence
    ports:
      - "8083:8083"
    networks:
      - chess-network
    env_file:
      - ./docker/secrets/mongo.env
    environment:
      DATABASE_HOST: mongodb
      DATABASE_PORT: 27017
      DATABASE_CONFIG: mongodb
    healthcheck:
      test: ["CMD-SHELL", "echo 'here'"]
      interval: 5s
      timeout: 30s
      retries: 10
      start_period: 35s
    depends_on:
      mongodb:
        condition: service_healthy

volumes:
  mongodb-data:
